[package]
name = "gameboy"
version = "0.1.0"
authors = ["Christopher Butcher <cbutcher@gmail.com>"]

[dependencies]
time = "0.1.36"
log = "0.3.6"
env_logger = "0.3"
clap = "2"
zmq = "0.8"

[dependencies.sdl2]
version = "0.29"
default-features = false
features = ["image","gfx"]

[dependencies.socket_state_reporter]
path = "../socket-state-reporter"

