max_width = 180
hard_tabs = false
tab_spaces = 2
array_layout = "Visual"
fn_args_layout = "Visual"

array_width = 6
comment_width = 400
fn_args_density = "Compressed"
normalize_comments = true
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
single_line_if_else_max_width = 120
fn_call_width = 120
spaces_within_square_brackets = true

struct_lit_style = "Block"
struct_lit_multiline_style = "PreferSingle"
struct_lit_width = 120
wrap_match_arms = true

chain_one_line_max = 120
